shfmt

diff --git a/bspwm/.local/bin/op-login b/bspwm/.local/bin/op-login
--- a/bspwm/.local/bin/op-login
+++ b/bspwm/.local/bin/op-login
@@ -5,39 +5,39 @@ MAX_RETRY=3
 retry=0
 
 login() {
-  set +e
-  OP_SESS_EVAL=$(zenity --password | op signin my 2>/dev/null)
-  set -e
-  eval $OP_SESS_EVAL
+	set +e
+	OP_SESS_EVAL=$(zenity --password | op signin my 2>/dev/null)
+	set -e
+	eval $OP_SESS_EVAL
 }
 
 check-op-status() {
-  set +e
-  op --cache --session $OP_SESSION_my list items >/dev/null 2>&1
-  LOGGED_IN=$?
-  set -e
+	set +e
+	op --cache --session $OP_SESSION_my list items >/dev/null 2>&1
+	LOGGED_IN=$?
+	set -e
 
-  if [ "$retry" -ge "$MAX_RETRY" ]; then
-    echo "max retries reached"
-    exit 1
-  fi
+	if [ "$retry" -ge "$MAX_RETRY" ]; then
+		echo "max retries reached"
+		exit 1
+	fi
 
-  if [ $LOGGED_IN -eq 127 ]; then
-    echo "1password CLI tool `op` not found"
-    exit 2
-  fi
+	if [ $LOGGED_IN -eq 127 ]; then
+		echo "1password CLI tool $(op) not found"
+		exit 2
+	fi
 
-  if [ ! $LOGGED_IN -eq 0 ]; then
-    retry=$((retry + 1))
-    login
-    check-op-status
-  else
-    op --session $OP_SESSION_my signin my
-  fi
+	if [ ! $LOGGED_IN -eq 0 ]; then
+		retry=$((retry + 1))
+		login
+		check-op-status
+	else
+		op --session $OP_SESSION_my signin my
+	fi
 }
 
 if [[ ! -v OP_SESSION_my ]]; then
-  login
+	login
 fi
 
 check-op-status
diff --git a/bspwm/.local/bin/sxhkd-chord-color b/bspwm/.local/bin/sxhkd-chord-color
--- a/bspwm/.local/bin/sxhkd-chord-color
+++ b/bspwm/.local/bin/sxhkd-chord-color
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-  echo "\
+	echo "\
 Usage: $(basename $0) -f FIFO_PATH -c BORDER_COLOR
 
 Set bspc config focused_border_color when sxhkd chord begins
@@ -16,77 +16,77 @@ Options:
 }
 
 exit_abnormal() {
-  usage
-  exit 1
+	usage
+	exit 1
 }
 
 DEBUG=0
 
 while getopts ":f:c:dh" options; do
-  case "${options}" in
-    f)
-      FIFO_PATH=${OPTARG}
-      if [[ ! -p $FIFO_PATH ]]; then
-        echo "Error: --fifo $FIFO_PATH not a FIFO pipe"
-        exit_abnormal
-      fi
-      ;;
-    c)
-      BORDER_COLOR=${OPTARG}
-      ;;
-    h)
-      usage
-      exit
-      ;;
-    d)
-      DEBUG=$((DEBUG + 1))
-      ;;
-    :)
-      echo "Error: -${OPTARG} requires an argument"
-      exit_abnormal
-      ;;
-    *)
-      exit_abnormal
-      ;;
-  esac
+	case "${options}" in
+		f)
+			FIFO_PATH=${OPTARG}
+			if [[ ! -p $FIFO_PATH ]]; then
+				echo "Error: --fifo $FIFO_PATH not a FIFO pipe"
+				exit_abnormal
+			fi
+			;;
+		c)
+			BORDER_COLOR=${OPTARG}
+			;;
+		h)
+			usage
+			exit
+			;;
+		d)
+			DEBUG=$((DEBUG + 1))
+			;;
+		:)
+			echo "Error: -${OPTARG} requires an argument"
+			exit_abnormal
+			;;
+		*)
+			exit_abnormal
+			;;
+	esac
 done
 
 if [ $# -eq 0 ]; then
-  echo "Error: No arguments provided"
-  exit_abnormal
+	echo "Error: No arguments provided"
+	exit_abnormal
 fi
 
 if [ -z "$BORDER_COLOR" ]; then
-  echo "Error: missing -c argument"
-  exit_abnormal
+	echo "Error: missing -c argument"
+	exit_abnormal
 fi
 
 if [ $DEBUG -gt 0 ]; then
-  echo "fifo: $FIFO_PATH"
-  echo "color: $BORDER_COLOR"
+	echo "fifo: $FIFO_PATH"
+	echo "color: $BORDER_COLOR"
 fi
 
 while :; do
-  while read -r message; do
-    if [ $DEBUG -gt 1 ]; then
-      echo $message
-    fi
-    prefix=${message:0:1}
-    case $prefix in
-      B)
-        LAST_COLOR=$(bspc config focused_border_color)
-        if [ $DEBUG -gt 0 ]; then
-          echo "Storing color: $LAST_COLOR"
-          echo "Setting color: $BORDER_COLOR"
-        fi
-        bspc config focused_border_color "$BORDER_COLOR"
-        ;;
-      E)
-        if [ $DEBUG -gt 0 ]; then
-          echo "Setting color: $LAST_COLOR"
-        fi
-        bspc config focused_border_color "$LAST_COLOR"
-    esac
-  done < $FIFO_PATH
+	while read -r message; do
+		if [ $DEBUG -gt 1 ]; then
+			echo $message
+		fi
+		prefix=${message:0:1}
+		case $prefix in
+			B)
+				LAST_COLOR=$(bspc config focused_border_color)
+				if [ $DEBUG -gt 0 ]; then
+					echo "Storing color: $LAST_COLOR"
+					echo "Setting color: $BORDER_COLOR"
+				fi
+				bspc config focused_border_color "$BORDER_COLOR"
+				;;
+			E)
+				if [ $DEBUG -gt 0 ]; then
+					echo "Setting color: $LAST_COLOR"
+				fi
+				bspc config focused_border_color "$LAST_COLOR"
+				;;
+		esac
+	done <$FIFO_PATH
 done
-
